package com.absinthe.libchecker.domain.appscan.usecase

import com.absinthe.libchecker.BuildConfig
import com.absinthe.libchecker.domain.appscan.AbiLabelFormatter
import com.absinthe.libchecker.domain.appscan.IndexedAppRepository
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import okio.buffer
import okio.sink

class ExportIndexedAppsReportUseCase(
  private val indexedAppRepository: IndexedAppRepository,
  private val abiLabelFormatter: AbiLabelFormatter
) {
  suspend operator fun invoke(
    outputStream: OutputStream,
    saveAsMarkDown: Boolean
  ) {
    outputStream.sink().buffer().use {
      val simpleDateFormat = SimpleDateFormat("yyyy-MM-dd, HH:mm:ss", Locale.getDefault())
      val formattedTime = simpleDateFormat.format(Date(System.currentTimeMillis()))
      it.writeUtf8("Generated by LibChecker ${BuildConfig.VERSION_NAME} (${BuildConfig.VERSION_CODE})${System.lineSeparator()}")
      it.writeUtf8("Generated at $formattedTime${System.lineSeparator()}")
      it.writeUtf8(System.lineSeparator())

      val list = indexedAppRepository.getIndexedApps()

      if (saveAsMarkDown) {
        it.writeUtf8("| Package Name | App Name | Version Name | Version Code | System App | Abi | Target SDK | Play Store Link | F-Droid Link |${System.lineSeparator()}")
        it.writeUtf8("|--------------|----------|--------------|--------------|------------|-----|------------|-----------------|--------------|${System.lineSeparator()}")

        list.forEach { item ->
          val abiString = abiLabelFormatter.getAbiLabel(item.abi.toInt())
          it.writeUtf8(
            "| ${item.packageName} | ${item.label} | ${item.versionName} | ${item.versionCode} | ${item.isSystem} | $abiString | ${item.targetApi} | [Link](https://play.google.com/store/apps/details?id=${item.packageName}) | [Link](https://f-droid.org/packages/${item.packageName}) |${System.lineSeparator()}"
          )
        }
      } else {
        list.forEach { item ->
          val abiString = abiLabelFormatter.getAbiLabel(item.abi.toInt())
          it.writeUtf8("Package name: ${item.packageName}${System.lineSeparator()}")
          it.writeUtf8("App name: ${item.label}${System.lineSeparator()}")
          it.writeUtf8("Version name: ${item.versionName}${System.lineSeparator()}")
          it.writeUtf8("Version code: ${item.versionCode}${System.lineSeparator()}")
          it.writeUtf8("System App: ${item.isSystem}${System.lineSeparator()}")
          it.writeUtf8("Abi: $abiString${System.lineSeparator()}")
          it.writeUtf8("Target SDK: ${item.targetApi}${System.lineSeparator()}")
          it.writeUtf8("Play Store Link: https://play.google.com/store/apps/details?id=${item.packageName}${System.lineSeparator()}")
          it.writeUtf8("F-Droid Link: https://f-droid.org/packages/${item.packageName}${System.lineSeparator()}")
          it.writeUtf8(System.lineSeparator())
        }
      }
    }
  }
}
